### ISSUE TITLE
ipinfo.io

### ISSUE THREAD

**Issue by ghost** [yoavst/whatIsMyIP#1]
Hey bro, I think http://ipinfo.io might be a better site for this purpose, see a
comparison

ipinfo.io/ip
http://wheresitup.com/results/5502ffc18c3dcf7c27072a8d

api.ipify.org
http://wheresitup.com/results/550300c58c3dcf962a072a8f

and as shown in my answer
http://stackoverflow.com/a/14594304

**Comment by yoavst** [comment]
> You are limited to 1,000 API requests per day. If you need to make more requests, or need SSL support, see our paid plans.

VS

> You can use it without limit (even if you're doing millions of requests per minute).
